{{- if .Values.blue.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine-ops.fullname" . }}-blue
  labels:
    {{- include "engine-ops.labels" . | nindent 4 }}
    version: blue
spec:
  replicas: {{ .Values.blue.replicas }}
  selector:
    matchLabels:
      {{- include "engine-ops.selectorLabels" . | nindent 6 }}
      version: blue
  template:
    metadata:
      labels:
        {{- include "engine-ops.selectorLabels" . | nindent 8 }}
        version: blue
    spec:
      serviceAccountName: {{ include "engine-ops.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.blue.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
---
{{- if .Values.green.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "engine-ops.fullname" . }}-green
  labels:
    {{- include "engine-ops.labels" . | nindent 4 }}
    version: green
spec:
  replicas: {{ .Values.green.replicas }}
  selector:
    matchLabels:
      {{- include "engine-ops.selectorLabels" . | nindent 6 }}
      version: green
  template:
    metadata:
      labels:
        {{- include "engine-ops.selectorLabels" . | nindent 8 }}
        version: green
    spec:
      serviceAccountName: {{ include "engine-ops.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.green.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
