apiVersion: v1
kind: Service
metadata:
  name: {{ include "engine-ops.fullname" . }}
  labels:
    {{- include "engine-ops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.blueGreen.enabled }}
  selector:
    {{- include "engine-ops.selectorLabels" . | nindent 4 }}
    version: {{ .Values.blueGreen.activeVersion }}
  {{- else }}
  selector:
    {{- include "engine-ops.selectorLabels" . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None

{{- if .Values.blueGreen.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "engine-ops.fullname" . }}-preview
  labels:
    {{- include "engine-ops.labels" . | nindent 4 }}
    service-type: preview
spec:
  type: ClusterIP
  selector:
    {{- include "engine-ops.selectorLabels" . | nindent 4 }}
    version: {{ .Values.blueGreen.inactiveVersion }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None
{{- end }}
