apiVersion: v2
name: monitoring
description: Prometheus and Grafana stack for Engine Ops
type: application
version: 0.1.0

dependencies:
  - name: prometheus
    version: "25.27.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "8.5.2"
    repository: "https://grafana.github.io/helm-charts"
