services:
  engineopsextension:
    image: engineopsextension
    build:
      context: extension
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
